name: Check & Test Jupyter Notebook execution

on:
  push:
    branches: 
      - main
  
  pull_request:
    types: [synchronize, review_requested]

jobs:
  check_solution:
    name: Test Solution folder
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo into GitHub's runner
        uses: actions/checkout@v2

        # Setup mini-conda environment
      - name: Setup Conda 
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: basics-of-data-analytics
          auto-activate-base: false

        # Install dependencies into conda env / Set globstar on to allow "**" pattern in bash
      - name: Install required dependencies 
        shell: bash -l {0}
        run: |
          curl -L -o test.tar.gz https://github.com/s-weigand/flake8-nb/archive/refs/tags/v0.3.0.tar.gz && \
            tar -xzf test.tar.gz && ls -la && \
            make ${GITHUB_WORKSPACE}/flake8-nb-0.3.0/ && \
            flake8_nb .
          pip install treon
      
      - name: Execute Treon for Solution 
        shell: bash -l {0}
        run: |
          for i in **/solution/**; do 
            treon "$i" 
          done

 

  