name: Test

on:
  push:
    branches: main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - shell: bash
        run: |
          bash --version
          shopt -s globstar
          shopt globstar
