name: Test

on:
  push:
    branches: main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: "3.9"

      - shell: bash
        run: |
          conda install matplotlib
          conda install pandas
          pip install treon

      - shell: bash
        run: |
          treon
