name: Test

on:
  push:
    branches: main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: "3.9"

      - shell: bash -l {0}
        run: |
          conda install matplotlib
          conda install pandas
          pip install treon
          shopt -s globstar
      
      - shell: bash -l {0}
        run: |
          for i in **/solution/**; do 
            treon "$i" || continue
          done


    
