name: Check & Test Jupyter Notebook execution

on:
  push:
    branches: 
      - main
  
  pull_request:
    types: [synchronize, review_requested]

jobs:
  check_solution:
    name: Test Solution folder
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo into GitHub's runner
        uses: actions/checkout@v2

        # Setup mini-conda environment
      - name: Setup Conda 
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: basics-of-data-analytics
          auto-activate-base: false
          python-version: 3.9

        # Install dependencies into conda env / Set globstar on to allow "**" pattern in bash
      - name: Install required dependencies 
        shell: bash -l {0}
        run: |
          pip install https://github.com/s-weigand/flake8-nb/archive/refs/tags/v0.3.0.tar.gz

          shopt -s globstar

          # for i in **/exercise/**.ipynb; do
          #  flake8_nb --select E9,F8 --notebook-cell-format '{nb_path}:code_cell#{code_cell_count}' "$i"
          # done

          find . ! -path '*/\.*' -type f -path '*/solution/*' -name "*.ipynb" -exec flake8_nb --notebook-cell-format '{nb_path}:code_cell#{code_cell_count}' '{}' \;
      

 

  