name: Check & Test Jupyter Notebook execution

on:
  push:
    branches: 
      - main
      - faris_add_codetest
  
  pull_request:
    types: [synchronize, review_requested]

jobs:
  check_solution:
    name: Test Solution folder
    runs-on: windows-latest
    steps:
      - name: Checkout repo into GitHub's runner
        uses: actions/checkout@v2

      - uses: actions/checkout@v2
      - name: Cache conda
        uses: actions/cache@v2
        env:
          # Increase this value to reset cache if etc/example-environment.yml has not changed
          CACHE_NUMBER: 0
        with:
          path: ~/conda_pkgs_dir
          key:
            ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{
            hashFiles('environment.yml') }}

        # Setup mini-conda environment
      - name: Setup Conda 
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: basics-of-data-analytics
          environment-file: "environment.yml"
          auto-activate-base: false

        # Install dependencies into conda env / Set globstar on to allow "**" pattern in bash
      - name: Install required dependencies 
        shell: bash -l {0}
        run: | 
          pip install treon
      
      - name: Execute Treon 
        shell: bash -l {0}
        run: |
          for i in **/solution/**; do 
            treon "$i" 
          done

  check_exercise:
    name: Test Exercise folder
    runs-on: windows-latest
    steps:
      - name: Checkout repo into GitHub's runner
        uses: actions/checkout@v2

      - uses: actions/checkout@v2
      - name: Cache conda
        uses: actions/cache@v2
        env:
          # Increase this value to reset cache if etc/example-environment.yml has not changed
          CACHE_NUMBER: 0
        with:
          path: ~/conda_pkgs_dir
          key:
            ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{
            hashFiles('environment.yml') }}

        # Setup mini-conda environment
      - name: Setup Conda 
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: basics-of-data-analytics
          environment-file: "environment.yml"
          auto-activate-base: false

        # Install dependencies into conda env / Set globstar on to allow "**" pattern in bash
      - name: Install required dependencies 
        shell: bash -l {0}
        run: |
          pip install treon
      
      - name: Execute Treon 
        shell: bash -l {0}
        run: |
          for i in **/exercise/**; do 
            treon "$i" || continue
          done


    
