name: Test

on:
  push:
    branches: main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        type: ["{S,s}olution", "{E,e}xercise"]
    steps:
      - uses: actions/checkout@v2

      - name: Cache conda
        uses: actions/cache@v2
        env:
          # Increase this value to reset cache if etc/example-environment.yml has not changed
          CACHE_NUMBER: 0
        with:
          path: ~/conda_pkgs_dir
          key:
            ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{ hashFiles('.env/environment.yml') }}

      - name: Setup Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: "3.9"
          environment-file: .env/environment.yml
          use-only-tar-bz2: true

      - shell: bash -l {0}
        run: |
          conda install matplotlib pandas
          pip install treon
          shopt -s globstar
      
      - shell: bash -l {0}
        run: |
          for i in **/${{ matrix.type }}/**; do 
            treon "$i" || continue
          done


    
